import type { PackingGroup, PackingPriority } from '@/types/database'

export const PACKING_GROUP_LABELS: Record<PackingGroup, string> = {
  outerwear: 'Waterproof / windproof outerwear',
  warm_layers: 'Warm layers',
  footwear: 'Footwear',
  car_essentials: 'Car / road essentials',
  electronics: 'Electronics',
  health_toiletries: 'Health / toiletries',
  documents_money: 'Documents / money',
  aurora_outdoor: 'Aurora / outdoor items',
  other: 'Other',
}

export const DEFAULT_PACKING_ITEMS: { group_name: PackingGroup; name: string; priority: PackingPriority; quantity: number }[] = [
  { group_name: 'outerwear', name: 'Waterproof windproof shell jacket', priority: 'essential', quantity: 1 },
  { group_name: 'outerwear', name: 'Waterproof over-trousers', priority: 'recommended', quantity: 1 },
  { group_name: 'outerwear', name: 'Warm insulated jacket / down layer', priority: 'essential', quantity: 1 },
  { group_name: 'warm_layers', name: 'Thermal base layers (top & bottom)', priority: 'essential', quantity: 2 },
  { group_name: 'warm_layers', name: 'Fleece or wool mid-layer', priority: 'essential', quantity: 2 },
  { group_name: 'warm_layers', name: 'Wool socks', priority: 'essential', quantity: 4 },
  { group_name: 'warm_layers', name: 'Beanie / warm hat', priority: 'essential', quantity: 1 },
  { group_name: 'warm_layers', name: 'Gloves', priority: 'essential', quantity: 1 },
  { group_name: 'warm_layers', name: 'Scarf / neck gaiter', priority: 'recommended', quantity: 1 },
  { group_name: 'footwear', name: 'Waterproof hiking boots', priority: 'essential', quantity: 1 },
  { group_name: 'footwear', name: 'Warm indoor/travel shoes', priority: 'recommended', quantity: 1 },
  { group_name: 'footwear', name: 'Wool/thermal socks (extra pairs)', priority: 'recommended', quantity: 2 },
  { group_name: 'car_essentials', name: 'International driving permit (if required)', priority: 'essential', quantity: 1 },
  { group_name: 'car_essentials', name: 'Offline map downloaded (Google Maps / maps.me)', priority: 'essential', quantity: 1 },
  { group_name: 'car_essentials', name: 'Phone car mount + charging cable', priority: 'recommended', quantity: 1 },
  { group_name: 'car_essentials', name: 'Snacks and water bottles for the car', priority: 'recommended', quantity: 1 },
  { group_name: 'electronics', name: 'Universal / EU power adapter', priority: 'essential', quantity: 2 },
  { group_name: 'electronics', name: 'Portable power bank', priority: 'recommended', quantity: 1 },
  { group_name: 'electronics', name: 'Camera + spare batteries/memory card', priority: 'optional', quantity: 1 },
  { group_name: 'health_toiletries', name: 'Personal medication', priority: 'essential', quantity: 1 },
  { group_name: 'health_toiletries', name: 'Lip balm and moisturizer (dry air/wind)', priority: 'recommended', quantity: 1 },
  { group_name: 'health_toiletries', name: 'Basic first-aid kit', priority: 'recommended', quantity: 1 },
  { group_name: 'documents_money', name: 'Passports', priority: 'essential', quantity: 2 },
  { group_name: 'documents_money', name: 'Driving licence', priority: 'essential', quantity: 1 },
  { group_name: 'documents_money', name: 'Travel insurance documents', priority: 'essential', quantity: 1 },
  { group_name: 'documents_money', name: 'Credit/debit cards + some cash (ISK)', priority: 'essential', quantity: 1 },
  { group_name: 'aurora_outdoor', name: 'Tripod (for aurora photography)', priority: 'optional', quantity: 1 },
  { group_name: 'aurora_outdoor', name: 'Head torch / flashlight', priority: 'recommended', quantity: 2 },
  { group_name: 'aurora_outdoor', name: 'Swimsuit (for geothermal pools)', priority: 'essential', quantity: 2 },
  { group_name: 'aurora_outdoor', name: 'Quick-dry towel', priority: 'recommended', quantity: 1 },
]
